name: atb_compression
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - git
  - curl
  - tar
  - xz
  - pigz
  - snakemake
  - agc=3.2.0
  - mbgc=2.0.1
  - seqkit=2.10.1
  - pip:
      - git+https://github.com/tam-km-truong/PhyloPack.git